language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
script:
  - py.test
before_install:
  - "pip install -U pip"
  - "pip  install color-changer"
  - "pip install opencv-python"
  - "pip install click"